name: Test the module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Disable Logger Outputs
        run: |
          sed -i "s/log_cli = true/log_cli = false/" pyproject.toml
      - name: Set up python environment
        uses: ./.github/actions/setup-python
      - name: Install the Project with Test Dependencies
        run: |
          make install-test
      - name: Test the Project
        run: |
          make test-all-parallel
